const products = [
	{
		name: "Laptop Nova X1",
		brand: "TechNova",
		description:
			"Ultrabook leggero con prestazioni elevate per professionisti in movimento",
		specs: "Intel Core i7, 16GB RAM, 512GB SSD, 14'' FHD, Wi-Fi 6",
		price: 1099.99,
		stock_quantity: 25,
		image_url: "laptop-icon-1.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Titan Pro",
		brand: "IronWare",
		description:
			"Potenza desktop in formato portatile, ideale per gaming e rendering",
		specs: "AMD Ryzen 9, 32GB RAM, 1TB SSD, RTX 4070, 17'' QHD",
		price: 1899.0,
		stock_quantity: 12,
		image_url: "laptop-icon-2.jpg",
		category_id: 1,
	},
	{
		name: "Laptop EcoLite 13",
		brand: "GreenByte",
		description:
			"Design minimal e consumi ridotti, perfetto per studenti e smart working",
		specs: "Intel Core i3, 8GB RAM, 256GB SSD, 13'' HD",
		price: 499.9,
		stock_quantity: 40,
		image_url: "laptop-icon-3.jpg",
		category_id: 1,
	},
	{
		name: "Laptop CreatorBook",
		brand: "PixelForge",
		description: "Pensato per creativi: schermo ad alta fedeltà e GPU dedicata",
		specs: "Intel Core i7, 16GB RAM, 1TB SSD, RTX 3050, 15.6'' 4K OLED",
		price: 1499.0,
		stock_quantity: 18,
		image_url: "laptop-icon-4.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Flex360",
		brand: "MobilityX",
		description: "Convertibile 2-in-1 con touchscreen e penna inclusa",
		specs: "Intel Core i5, 8GB RAM, 512GB SSD, 14'' FHD Touch",
		price: 899.0,
		stock_quantity: 30,
		image_url: "laptop-icon-5.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Stealth Air",
		brand: "SilentTech",
		description:
			"Sottile e silenzioso, con raffreddamento passivo e autonomia estesa",
		specs: "Intel Core M, 8GB RAM, 256GB SSD, 13'' FHD",
		price: 649.0,
		stock_quantity: 22,
		image_url: "laptop-icon-6.jpg",
		category_id: 1,
	},
	{
		name: "Laptop Quantum Edge",
		brand: "CoreLogic",
		description: "Prestazioni bilanciate per lavoro e intrattenimento",
		specs: "AMD Ryzen 5, 16GB RAM, 512GB SSD, 15.6'' FHD",
		price: 799.0,
		stock_quantity: 35,
		image_url: "laptop-icon-7.jpg",
		category_id: 1,
	},
	{
		name: "Laptop UrbanGo",
		brand: "CityTech",
		description: "Compatto e resistente, ideale per la mobilità urbana",
		specs: "Intel Core i5, 8GB RAM, 256GB SSD, 12.5'' HD",
		price: 599.0,
		stock_quantity: 28,
		image_url: "laptop-icon-8.jpg",
		category_id: 1,
	},
	{
		name: "Laptop VisionBook",
		brand: "ConnectPro",
		description: "Ottimizzato per videoconferenze e collaborazione remota",
		specs: "Intel Core i5, 16GB RAM, 512GB SSD, Webcam HD, 15'' FHD",
		price: 849.0,
		stock_quantity: 20,
		image_url: "laptop-icon-9.jpg",
		category_id: 1,
	},
	{
		name: "Laptop ZenStation",
		brand: "ZenCore",
		description: "Esperienza fluida e silenziosa per ambienti professionali",
		specs: "AMD Ryzen 7, 16GB RAM, 1TB SSD, 15.6'' QHD",
		price: 1199.0,
		stock_quantity: 15,
		image_url: "laptop-icon-10.jpg",
		category_id: 1,
	},
];

module.exports = products;
