const orderItems = [
		{
			order_item_id: 1,
			order_id: 1,
			product_id: 1,
			name: "Mouse Wireless",
			description: "Mouse ergonomico con connessione Bluetooth",
			specs: "800–1600 DPI, batteria ricaricabile",
			price: 29.9,
			quantity: 1,
			price_at_purchase: 29.9,
		},
		{
			order_item_id: 2,
			order_id: 1,
			product_id: 2,
			name: "Tappetino Mouse",
			description: "Tappetino antiscivolo in neoprene",
			specs: "Dimensioni 25x20 cm, colore nero",
			price: 9.9,
			quantity: 2,
			price_at_purchase: 19.8,
		},
		{
			order_item_id: 3,
			order_id: 2,
			product_id: 3,
			name: "Cuffie Over-Ear",
			description: "Cuffie con cancellazione del rumore",
			specs: "Bluetooth 5.0, autonomia 20h",
			price: 89.0,
			quantity: 1,
			price_at_purchase: 89.0,
		},
		{
			order_item_id: 4,
			order_id: 2,
			product_id: 4,
			name: "Power Bank 10000mAh",
			description: "Caricatore portatile USB-C",
			specs: "2 porte USB, ricarica rapida",
			price: 60.5,
			quantity: 1,
			price_at_purchase: 60.5,
		},
		{
			order_item_id: 5,
			order_id: 3,
			product_id: 5,
			name: "Supporto Laptop",
			description: "Supporto regolabile in alluminio",
			specs: "Compatibile fino a 17 pollici",
			price: 59.0,
			quantity: 1,
			price_at_purchase: 59.0,
		},
		{
			order_item_id: 6,
			order_id: 4,
			product_id: 6,
			name: "Zaino Tech",
			description: "Zaino impermeabile con porta USB",
			specs: "Capacità 25L, tasche imbottite",
			price: 65.0,
			quantity: 1,
			price_at_purchase: 65.0,
		},
		{
			order_item_id: 7,
			order_id: 4,
			product_id: 7,
			name: "Notebook A5",
			description: "Quaderno con copertina rigida",
			specs: "80 fogli, carta riciclata",
			price: 5.0,
			quantity: 3,
			price_at_purchase: 15.0,
		},
		{
			order_item_id: 8,
			order_id: 4,
			product_id: 8,
			name: "Penna Gel",
			description: "Penna a inchiostro nero",
			specs: "Punta 0.7mm, impugnatura morbida",
			price: 2.0,
			quantity: 5,
			price_at_purchase: 10.0,
		},
		{
			order_item_id: 9,
			order_id: 2,
			product_id: 9,
			name: "Adattatore USB-C",
			description: "Adattatore multiporta HDMI/USB",
			specs: "Compatibile con Mac e Windows",
			price: 35.0,
			quantity: 1,
			price_at_purchase: 35.0,
		},
		{
			order_item_id: 10,
			order_id: 1,
			product_id: 10,
			name: "Custodia Laptop",
			description: "Custodia imbottita 15.6 pollici",
			specs: "Materiale neoprene, colore grigio",
			price: 40.2,
			quantity: 1,
			price_at_purchase: 40.2,
		},
	];

  module.exports = orderItems;  